spring.application.name=task management

server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/cursoKeycloakdb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=hrm-user
spring.datasource.password=hrm
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true