spring:
  keycloak:
    endpoint: http://localhost:8080
    id: admin-cli
    username-keycloak: admin
    password-keycloak: admin
    grant-type: password
    uri-access-token-admin: /realms/master/protocol/openid-connect/token
    uri-create-user: /admin/realms/schedule-task/users
    uri-reset-password: /admin/realms/schedule-task/users/{id}/reset-password
    uri-execute-email-valid-user: /admin/realms/schedule-task/users/{userId}/execute-actions-email
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/schedule-task

  application:
    name=Task Management
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: cursoKeycloakdb
  generate-ddl: true
  hibernate:
    ddl-auto: validate
  open-in-view: true

  datasource:
    url: jdbc:mysql://localhost:3306/cursoKeycloakdb?allowPublicKeyRetrieval=true&useSSL=false
    username: hrm_user
    password: hrm
    drive-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enable: true
    baseline-on-migrate: true
server:
  port: 8081